Isolaatti/Pages/SettingsPages/ChangePassword.cshtml.cs
using System.Threading.Tasks;
using Isolaatti.Accounts.Service;
using Isolaatti.Utils;
using Isolaatti.Utils.Attributes;
using Microsoft.AspNetCore.Mvc;

namespace Isolaatti.Pages.SettingsPages
{
    [IsolaattiAuth]
    public class ChangePassword : IsolaattiPageModel
    {
        private readonly IAccountsService _accounts;

        public ChangePassword(IAccountsService accounts)
        {
            _accounts = accounts;
        }

        [BindProperty] public string CurrentPassword { get; set; }

        [BindProperty] public string NewPassword { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (CurrentPassword == null || NewPassword == null)
            {
                return RedirectToPage("MyProfile", new
                {
                    errorChangingPass = true
                });
            }
            
            if (!(await _accounts.ChangeAPassword(User.Id, CurrentPassword, NewPassword)).Success)
            {
                return RedirectToPage("MyProfile", new
                {
                    currentPasswordIsWrong = true
                });
            }

            return Redirect("/LogOutPage");
        }
    }
}

Isolaatti/Pages/SettingsPages/FeedSettingsContent.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Isolaatti.Models;
using Isolaatti.Utils;
using Isolaatti.Utils.Attributes;
using Microsoft.AspNetCore.Mvc;

namespace Isolaatti.Pages.SettingsPages;
[IsolaattiAuth]
public class FeedSettingsContent : IsolaattiPageModel
{
    private readonly DbContextApp _db;

    public FeedSettingsContent(DbContextApp dbContextApp)
    {
        _db = dbContextApp;
    }

    [BindProperty] public bool ShowOwnPostsOnFeed { get; set; }
    [BindProperty] public bool PreferencesUpdated { get; set; }

    public async Task<IActionResult> OnGet()
    {
        ShowOwnPostsOnFeed = _db.FollowerRelations.Any(fr => fr.TargetUserId == User.Id && fr.UserId == User.Id);
        return Page();
    }

    public async Task<IActionResult> OnPostShowOwnPostsSet()
    {
        if (_db.FollowerRelations.Any(fr => fr.TargetUserId == User.Id && fr.UserId == User.Id) == ShowOwnPostsOnFeed)
        {
            PreferencesUpdated = true;
            return Page();
        }

        if (ShowOwnPostsOnFeed)
        {
            _db.FollowerRelations.Add(new FollowerRelation
            {
                UserId = User.Id,
                TargetUserId = User.Id
            });
        }
        else
        {
            var frToDelete = _db.FollowerRelations
                .Single(fr => fr.UserId == User.Id && fr.TargetUserId == User.Id);

            _db.FollowerRelations.Remove(frToDelete);
        }

        PreferencesUpdated = true;

        await _db.SaveChangesAsync();
        return Page();
    }
}

Isolaatti/Pages/SettingsPages/PrivacySettings.cshtml.cs
using System.Threading.Tasks;
using Isolaatti.Accounts.Service;
using Isolaatti.Models;
using Isolaatti.Utils;
using Isolaatti.Utils.Attributes;
using Microsoft.AspNetCore.Mvc;

namespace Isolaatti.Pages.SettingsPages
{
    [IsolaattiAuth]
    public class PrivacySettings : IsolaattiPageModel
    {
        private readonly DbContextApp _db;
        private readonly IAccountsService _accounts;

        public PrivacySettings(DbContextApp dbContextApp, IAccountsService accounts)
        {
            _db = dbContextApp;
            _accounts = accounts;
        }

        [BindProperty] public bool ShowEmail { get; set; }
        [BindProperty] public bool PreferencesUpdated { get; set; }

        public IActionResult OnGet()
        {
            ShowEmail = User.ShowEmail;
            return Page();
        }


        public async Task<IActionResult> OnPostEmailPrivacy()
        {
            User.ShowEmail = ShowEmail;
            _db.Users.Update(User);
            await _db.SaveChangesAsync();
            PreferencesUpdated = true;
            return Page();
        }
    }
}

Isolaatti/Pages/SettingsPages/Sessions.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Isolaatti.Accounts;
using Isolaatti.Accounts.Service;
using Isolaatti.Services;
using Isolaatti.Utils;
using Isolaatti.Utils.Attributes;
using Microsoft.AspNetCore.Mvc;

namespace Isolaatti.Pages.SettingsPages
{
    [IsolaattiAuth]
    public class Sessions : IsolaattiPageModel
    {
        private readonly IAccountsService _accounts;
        public IEnumerable<Models.MongoDB.Session> SessionTokens;

        public Sessions(IAccountsService accounts)
        {
            _accounts = accounts;
        }

        public async Task<IActionResult> OnGet()
        {
            SessionTokens = await _accounts.GetSessionsOfUser(User.Id);

            return Page();
        }
    }
}

Isolaatti/Pages/SettingsPages/ChangePassword.cshtml
@page "/ajustes/cambiar_contra"
@model Isolaatti.Pages.SettingsPages.ChangePassword

@{
    Layout = "Shared/_LayoutWebApp";
    ViewData["Title"] = "Cambia tu contraseña";
}
<div class="container">
    <div class="row m-0">
        <div class="col-lg-3 col-md-2"></div>
        <div class="col-lg-6 col-md-8">
            <h5 class="mt-3 text-center"><i class="fas fa-cog"></i> Ajustes</h5>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-page="/Settings">Ajustes</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Cambiar contraseña</li>
                </ol>
            </nav>
            <div class="d-flex justify-content-center">
                <div class="card mt-2 max-500px">
                    <h5 class="card-header">Cambia tu contraseña</h5>
                    <div class="card-body">
                        <p class="card-text">Después de este proceso, tendrás que inicar sesión de nuevo</p>
                        <form method="post" id="change-password-form">
                            <input type="hidden" name="userId" value="@ViewData["userId"]">
                            <div class="form-group">
                                <label for="current_password_field">Contraseña actual</label>
                                <input type="password" asp-for="CurrentPassword" class="form-control"
                                       id="current_password_field" required autocomplete="false">
                                <div class="invalid-feedback">
                                    La contraseña actual proporcionada es incorrecta. Inténtalo de nuevo
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Nueva contraseña</label>
                                <input type="password" asp-for="NewPassword" class="form-control"
                                       id="new_password_field" required autocomplete="false">
                            </div>
                            <div class="form-group">
                                <label for="new_password_conf_field">Confirma nueva contraseña</label>
                                <input type="password" class="form-control"
                                       id="new_password_conf_field" required autocomplete="false">
                            </div>
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">Continuar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <p class="mt-3">Otros vínculos: <a asp-page="/Sessions">Consulta donde has iniciado sesión.</a></p>
        </div>
        <div class="col-lg-3 col-md-2"></div>
    </div>
</div>

Isolaatti/Pages/SettingsPages/FeedSettingsContent.cshtml
@page "/ajustes/feed/contenido"
@model Isolaatti.Pages.SettingsPages.FeedSettingsContent

@{
    Layout = "Shared/_LayoutWebApp";
    ViewData["Title"] = "Ajustes del contenido del feed";
}
<div class="container">
    <div class="row m-0">
        <div class="col-lg-3 col-md-2"></div>
        <div class="col-lg-6 col-md-8">
            <h5 class="mt-3 text-center"><i class="fas fa-cog"></i> Ajustes</h5>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-page="/Settings">Ajustes</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Contenido del feed</li>
                </ol>
            </nav>
            
            @if (Model.PreferencesUpdated)
            {
                <div class="alert alert-info alert-dismissible">
                    Preferencias actualizadas exitosamente
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
                </div>
            }
            <p>Gestiona los parametros que definen el contenido de tu feed.</p>
            <form method="post" asp-page-handler="ShowOwnPostsSet">
                <div class="custom-control custom-switch">
                    <input class="custom-control-input" id="switch-feed-settings-show-own-content" asp-for="ShowOwnPostsOnFeed"/>
                    <label class="custom-control-label" for="switch-feed-settings-show-own-content">
                        Mostrar tus discusiones no privadas en tu feed
                    </label>
                </div>
                <div class="d-flex justify-content-end">
                    <button class="btn btn-primary">
                        Guardar
                    </button>
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-md-2"></div>
    </div>
</div>

Isolaatti/Pages/SettingsPages/PrivacySettings.cshtml
@page "/ajustes/privacidad"
@model Isolaatti.Pages.SettingsPages.PrivacySettings

@{
    Layout = "Shared/_LayoutWebApp";
    ViewData["Title"] = "Ajustes de privacidad";

}
<div class="container">
    <div class="row m-0">
        <div class="col-lg-3 col-md-2"></div>
        <div class="col-lg-6 col-md-8">
            <h5 class="mt-3 text-center"><i class="fas fa-cog"></i> Ajustes</h5>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-page="/Settings">Ajustes</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Privacidad</li>
                </ol>
            </nav>
            @if (Model.PreferencesUpdated)
            {
                <div class="alert alert-info alert-dismissible">
                    Preferencias actualizadas exitosamente
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
                </div>
            }

            <form method="post" asp-page-handler="EmailPrivacy">
                <div class="custom-control custom-switch">
                    <input class="custom-control-input" id="switch-privacy-show-email" asp-for="ShowEmail">
                    <label class="custom-control-label" for="switch-privacy-show-email">Tu dirección de correo se les muestra a los demás en tu perfil</label>
                </div>
    
                <div class="d-flex justify-content-end mt-3">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                </div>
            </form>
    
        </div>
        <div class="col-lg-3 col-md-2"></div>
    </div>
</div>

Isolaatti/Pages/SettingsPages/Sessions.cshtml
@page "/ajustes/sesiones_recordadas"
@model Isolaatti.Pages.SettingsPages.Sessions

@{
    Layout = "Shared/_LayoutWebApp";
    ViewData["Title"] = "Sesiones guardadas";

}
<div class="row m-0">
    <div class="col-lg-3 col-md-2"></div>
    <div class="col-lg-6 col-md-8">
        <h5 class="mt-3 text-center"><i class="fas fa-cog"></i> Ajustes</h5>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a asp-page="/Settings">Ajustes</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Sesiones guardadas</li>
            </ol>
        </nav>
        <p>Estas son los dispositivos y navegadores donde has iniciado sesión.</p>
        <div class="list-group">
            @foreach (var sessionToken in Model.SessionTokens)
            {
                <div class="list-group-item">
                    <h6>@sessionToken.IpAddress</h6>
                    <h6>@sessionToken.CreationDate</h6>
                    <small>@sessionToken.UserAgent</small>
                </div>
            }
        </div>
        <div class="list-group list-group-flush mt-2">
            <a class="list-group-item list-group-item-action" asp-page="/LogOutPage">Cerrar sesión</a>
        </div>
    </div>
    <div class="col-lg-3 col-md-2"></div>
</div>